services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: ses-kanri-app-prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always 
