services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ses-kanri-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    command: npm run dev 
